--- # creating a folder
- hosts: all
  become: yes
  connection: ssh
  user: ansible




  tasks: 
     - name: folder creation
       file:
         path: /home/ansible/myfolder
         state: directory
